services:
  giftlock-db:
    image: postgres:16
    restart: always
    user: postgres
    volumes:
      - giftlock-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=giftlockpassword
      - POSTGRES_DB=giftlock
      - POSTGRES_USER=giftlockuser
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "giftlockuser", "-d", "giftlock"]
      interval: 10s
      timeout: 5s
      retries: 5

  giftlock-app:
    build:
      context: .
    depends_on:
      - giftlock-db
    ports:
      - "8080:8080"
    env_file:
      - .env
    profiles:
      - app


volumes:
  giftlock-db-data:
